version: "3.8"

services:
  karaf:
    build: weather-fetcher
    container_name: karaf
    ports:
      - "8181:8181"
      - "1099:1099"
      - "44444:44444"
      - "8101:8101"
    depends_on:
      - mariadb
    links:
      - mariadb
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    hostname: weatherdb
    environment:
      MYSQL_DATABASE: weather
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3366:3306"
    restart: always
  app:
    build: weather-fetcher-stats
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - mariadb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/weather
